AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'spec/*_helper.rb'

Style/Documentation:
  Enabled: false

Style/AndOr:
  Enabled: false
