# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0de2d694fad8899a1105a2a81ecca23bf6ba10258e3e76dd307fa14dff78200227e1ee5b76051e5c94ab1363c3768155b1bb4b459a88190b251729200716c734
  redis_url: "redis://localhost:6379/0"

test:
  secret_key_base: 1441052cba215a1fdaf337756ab6e51c1d2b1bc4175f8610069f97f92385848be8db5c339e19706d3690f359f0bcac401c2491f42484a9ca89b8e9b03a878c6c
  redis_url: "redis://localhost:6379/1"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  redis_url: <%= ENV['REDISTOGO_URL'] %>
